server:
  port: 3301
spring:
    application:
      name: imc  # 应用名称
    cloud:
       config:
          server:
            git:
              uri: https://github.com/renqignsong/imcconfig #配置文件所在仓库
              username: qingsong.ren@samsungimc.com
              password: imc1680011
              default-label: master #配置文件分支
              search-paths: imcconfig  #配置文件所在根目录